### ISSUE TITLE
Issue with 10Gbps interface threshold alert

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/plugin_thold#251]
Please refer https://github.com/Cacti/cacti/issues/2395 
looks like its a bug.. please help to fix this.

**Comment by cigamit** [comment]
Should be resolved now.  Must be running 1.2.2+

**Comment by vishnubraj** [comment]
@cigamit  do you mean cacti 1.2.2 ? can i download the develop branch and try it now?

**Comment by netniV** [comment]
Develop branch should be fairly stable.  If you are already running 1.2 or above, I would upgrade to it.  We may be releasing that this weekend all being well.

**Comment by vishnubraj** [comment]
i just updated the cacti and thold plugin to latest version.. i still see the current values are not correct..
Can you please check this.. 

<img width="1424" alt="screenshot 2019-02-25 at 3 03 45 pm" src="https://user-images.githubusercontent.com/11851188/53374885-92661600-390e-11e9-981b-ec14300441cb.png">

**Comment by TheWitness** [comment]
Looks good to me.  Edit the thold and send a screen shot of the graph along with the tabs showing current data.  Remember, the data is raw, likely KB/sec (octets/sec) in thold.  But the graph could be in bit's/second.

**Comment by vishnubraj** [comment]
no @TheWitness  the current data is after CDEF calculation, i have the other graphs with less than 1Gbps traffic and has the correct percent value in the current 

<img width="1120" alt="screenshot 2019-02-25 at 7 13 52 pm" src="https://user-images.githubusercontent.com/11851188/53385054-f817c980-3931-11e9-85f4-98075e5805ea.png">


**Working one**

<img width="1220" alt="screenshot 2019-02-25 at 7 15 40 pm" src="https://user-images.githubusercontent.com/11851188/53385034-e33b3600-3931-11e9-9a10-5ee923f582d4.png">

**Comment by netniV** [comment]
I think this is less a THold issue and more that your data is stored differently for the 20G interface graph.  Can you provide the data source info mode to show the data source values for both?  And also, let us know what CDEF's or Threshold configurations you have in place for these two.

**Comment by TheWitness** [comment]
I think I see what he is talking about.  It's the display value on the tab itself?  Let's get a scree capture of both tholds as well, the entire form.

**Comment by vishnubraj** [comment]
Below is the data source info for the graph which shows correct value when the traffic is less than 1Gbps...

<img width="1260" alt="screenshot 2019-02-27 at 11 02 01 am" src="https://user-images.githubusercontent.com/11851188/53515582-2e169400-3a7f-11e9-8291-f13c34412963.png">

CDEF function

<img width="1266" alt="screenshot 2019-02-27 at 11 04 22 am" src="https://user-images.githubusercontent.com/11851188/53515698-7fbf1e80-3a7f-11e9-9bf6-085da1d8dc7c.png">

**Comment by cigamit** [comment]
I think that @TheWitness was asking for the Threshold Edit pages.  Looks like the Info page is wrong though.  That should be logged as a bug.  The 200xxx number is correct.

**Comment by vishnubraj** [comment]
<img width="1258" alt="screenshot 2019-02-28 at 4 51 02 am" src="https://user-images.githubusercontent.com/11851188/53567981-b0519780-3b15-11e9-9e0a-f3e0f69d2bab.png">
<img width="1256" alt="screenshot 2019-02-28 at 4 51 19 am" src="https://user-images.githubusercontent.com/11851188/53567990-b5aee200-3b15-11e9-8492-8a27a80cd360.png">

**Comment by vishnubraj** [comment]
Did you guys get a chance to check this?

**Comment by TheWitness** [comment]
Can you show me the full form for both the working and non-working examples?  I'm sure I'm not getting this right.  Also, need to see the CDEF definition.

**Comment by vishnubraj** [comment]
Working one with Less 1Gbps traffic..
<img width="1149" alt="Working Graph" src="https://user-images.githubusercontent.com/11851188/54245246-139bea80-4556-11e9-81de-4cc6754a1466.png">

Not working one with More than 1Gbps traffic..

<img width="1127" alt="Not Working Graph" src="https://user-images.githubusercontent.com/11851188/54245260-1f87ac80-4556-11e9-8ab9-d88a417072a3.png">


CDEF Function:

<img width="809" alt="Screenshot 2019-03-13 at 6 07 54 AM" src="https://user-images.githubusercontent.com/11851188/54245318-69709280-4556-11e9-8115-e5ee6ddb737e.png">

**Comment by vishnubraj** [comment]
the traffic_in last or traffic_out last are showing the value after CDEF function... for the working ones it shows correct.. But not working ones shows a higher value.. The above screen shot is taken from the threshold edit page..

**Comment by vishnubraj** [comment]
@netniV This issue is not fixed... can you please reopen the same?

**Comment by c0sm1n** [comment]
I'd like to see if we can reopen this issue as after upgrading the thold plugin to the latest develop branch I started experiencing a similar issue as described in the earlier post, except that my problem appears to be tied to the current bandwidth utilization reported by thold rather than the interface speed. 

When tracking bandwidth utilization, the percentage is reported correctly while under 100Mbps. Once the util (traffic_in or traffic_out) exceeds 100 Mbps, a unit gets appended to the current value and it incorrectly reports a threshold crossing. 

<img width="1035" alt="Screen Shot 2022-02-10 at 9 37 52 AM" src="https://user-images.githubusercontent.com/26253207/153442600-62b8a934-5053-43ad-8711-4ce13139b1ea.png">

<img width="1196" alt="Screen Shot 2022-02-10 at 9 37 03 AM" src="https://user-images.githubusercontent.com/26253207/153442536-14756469-624b-4599-bb0a-0709288be5f1.png">

<img width="1319" alt="Screen Shot 2022-02-10 at 9 37 30 AM" src="https://user-images.githubusercontent.com/26253207/153442452-02592e2d-4f58-46fc-9a74-3592fece51d5.png">
![Screen Shot 2022-02-10 at 9 27 45 AM](https://user-images.githubusercontent.com/26253207/153442638-298afe38-9f16-4e06-936f-c75b6ab9b80d.png)
