### ISSUE TITLE
Thold daemon setting causing warningsThold not running

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/plugin_thold#295]
I am running the develop version on thold and its not running..

getting the below error frequently.

```

2019/04/12 04:38:14 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[771]:CactiErrorHandler())
--
2019/04/12 04:38:14 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 771
2019/04/12 04:38:14 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[732]:CactiErrorHandler())
2019/04/12 04:38:14 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 732

```

**Comment by TheWitness** [comment]
This is resolved.  Update to the latest develop.  Those warnings should disappear.  Close if warnings are gone.

**Comment by vishnubraj** [comment]
@TheWitness  i updated both cacti and Thold plugin to develop version, but still i am getting the below mentioned error.
```

2019/04/17 05:15:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[758]:CactiErrorHandler())
--
2019/04/17 05:15:08 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 758
2019/04/17 05:15:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[758]:CactiErrorHandler())
2019/04/17 05:15:08 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 758
2019/04/17 05:15:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[758]:CactiErrorHandler())
2019/04/17 05:15:08 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 758
2019/04/17 05:15:08 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[360]:thold_get_currentval(), /plugins/thold/thold_functions.php[758]:CactiErrorHandler())


```

**Comment by TheWitness** [comment]
@vishnubraj, I've just done another commit.  Let's see what errors you get next.

**Comment by vishnubraj** [comment]
Thanks @TheWitness ... Errors are gone.. But thold is still not sending any alerts.. no syslog alert also.

**Comment by vishnubraj** [comment]
i take it back.. i am still receiving the below error.

```

2019/04/22 13:47:11 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[368]:thold_build_cdef(), /plugins/thold/thold_functions.php[3644]:thold_rpn(), /plugins/thold/thold_functions.php[3681]:CactiErrorHandler())
--
2019/04/22 13:47:11 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 3681
2019/04/22 13:47:11 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[368]:thold_build_cdef(), /plugins/thold/thold_functions.php[3644]:thold_rpn(), /plugins/thold/thold_functions.php[3681]:CactiErrorHandler())
2019/04/22 13:47:11 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 3681
2019/04/22 13:47:11 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[368]:thold_build_cdef(), /plugins/thold/thold_functions.php[3644]:thold_rpn(), /plugins/thold/thold_functions.php[3681]:CactiErrorHandler())
2019/04/22 13:47:11 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 3681
2019/04/22 13:47:11 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[368]:thold_build_cdef(), /plugins/thold/thold_functions.php[3644]:thold_rpn(), /plugins/thold/thold_functions.php[3681]:CactiErrorHandler())
2019/04/22 13:47:11 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 3681
2019/04/22 13:47:11 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php[676]:process_poller_output(), /lib/poller.php[532]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_poller_output(), /plugins/thold/includes/polling.php[368]:thold_build_cdef(), /plugins/thold/thold_functions.php[3644]:thold_rpn(), /plugins/thold/thold_functions.php[3681]:CactiErrorHandler())
2019/04/22 13:47:11 - ERROR PHP WARNING in Plugin 'thold': A non-numeric value encountered in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 3681


```

**Comment by cigamit** [comment]
Somehow your thold does not align with the develop version.  You should be using all of develop.
